spring:
  mail:
    test-connection: true
    protocol: smtps
    host: smtp.yandex.ru
    port: 465
    username: usedreamless@yandex.ru
    password: hnbngpfvxqxnxyxn
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true

  datasource:
    url: jdbc:postgresql://localhost:5432/emergency_notifications_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true

business:
  message: 'Dear, %s!<br><br>This message is forwarded from Emergency Notification System.<br>Please contact with %s by email: %s'
  telegram-username-regex: ^@[a-zA-Z0-9]+$
  email-regex: ^[a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+\.[a-zA-Z0-9_-]+$
  mail-subject: '[ENS] Emergency Call From'