CREATE TYPE service AS ENUM ('TELEGRAM', 'EMAIL');

CREATE CAST (varchar AS service) WITH INOUT AS IMPLICIT;

CREATE SEQUENCE caller_id_seq MINVALUE 5 INCREMENT 5;

CREATE TABLE IF NOT EXISTS caller (
id BIGINT PRIMARY KEY default nextval('caller_id_seq'),
username VARCHAR UNIQUE NOT NULL,
password VARCHAR NOT NULL,
email VARCHAR UNIQUE NOT NULL,
message VARCHAR,
image VARCHAR
);

CREATE TABLE IF NOT EXISTS role (
name VARCHAR PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS callertorole (
id BIGINT PRIMARY KEY,
role_name VARCHAR NOT NULL REFERENCES role(name) ON DELETE CASCADE ON UPDATE CASCADE,
caller_id BIGINT NOT NULL REFERENCES caller(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE SEQUENCE binding_id_seq MINVALUE 14 INCREMENT 5;

CREATE TABLE IF NOT EXISTS caller2receiver_binding (
id BIGINT PRIMARY KEY default nextval('binding_id_seq'),
caller_id BIGINT NOT NULL REFERENCES caller(id) ON DELETE CASCADE ON UPDATE CASCADE,
receiver VARCHAR NOT NULL,
service service NOT NULL,
service_link VARCHAR NOT NULL
);

CREATE SEQUENCE emergency_id_seq MINVALUE 7 INCREMENT 5;

CREATE TABLE IF NOT EXISTS emergency_calls (
id BIGINT PRIMARY KEY default nextval('emergency_id_seq'),
binding_id BIGINT NOT NULL REFERENCES caller2receiver_binding(id) ON DELETE CASCADE ON UPDATE CASCADE,
date_called TIMESTAMP NOT NULL,
date_received TIMESTAMP
);